### ISSUE TITLE
What's the deal with issues anyway?

### ISSUE THREAD

**Issue by rlane85** [Blane245/lane-db-test#1]
Can I edit this later and add a link? Let's see!

Edit: yep!

**Comment by Blane245** [comment]
what the heck! I guess this works directly, but not with VS Code.

**Comment by Blane245** [comment]
I have started issues on the lane-db repo.

**Comment by rlane85** [comment]
> what the heck! I guess this works directly, but not with VS Code.

Oh, yep it’s probably an auth issue within your vs code remote session. If you’d like to be able to handle issues, PRs, or other GitHub things that aren’t working it is probably a relatively simple solution. I just used the mobile GitHub app to make this issue and edit it
